In [1]:
import pennylane as qml
from pennylane import numpy as np

In [179]:
def circuit_left():
    """
    This function corresponds to the circuit on the left-hand side of the diagram in the 
    description. Simply place the necessary operations, you do not have to return anything.
    """
#    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0,1])
    qml.CNOT(wires=[1,2])
#    qml.Hadamard(wires=0)
    #qml.measure(wires=[0,1], observable=qml.PauliZ @ qml.PauliZ)    
#    qml.U3(-alpha, -beta, -gamma, wires=0)
    #qml.expval(qml.PauliZ(0))   

@qml.qnode(dev)
def prob_meas(wires):
    return qml.probs(wires)
    
def circuit_right():
    """
    This function corresponds to the circuit on the right-hand side of the diagram in the 
    description. Simply place the necessary operations, you do not have to return anything.
    """
    #result = qml.expval(-0.5*qml.PauliZ(0) - qml.PauliZ(1) + 0.5*qml.PauliZ(2))
    #if result == 0:
     #   qml.PauliX(wires=0)
    #elif result == 1:
     #   qml.PauliX(wires=1)
    #elif result == -2:
        #qml.PauliX(wires=2)
   # qml.invert(qml.measure)(wires=[0,1,2])
    #qml.adjoint(qml.measure)
    #qml.U3(alpha, beta, gamma, wires=0)
    #qml.CNOT(wires=[0,1])
    #qml.CNOT(wires=[1,2])
    
    #qml.PauliX(wires=0)
    #qml.PauliX(wires=1)
    #qml.ctrl(qml.CNOT, control=0)(wires=[1,2])
    #result = qml.expval(qml.PauliZ(0) - qml.PauliZ(1))
    #if result == 0:
     #   qml.PauliX(wires=2)
    
    probs = prob_meas([0,1])
#    qml.cond(probs.numpy()[0] == probs.numpy()[1], qml.PauliX)(wires=2)
    if np.allclose(probs[0], probs[1]):
        qml.PauliX(2)

In [187]:
def U():
    """This operator generates a PauliX gate on a random qubit"""
    qml.PauliX(wires=np.random.randint(3))


dev = qml.device("default.qubit", wires=3)

@qml.qnode(dev)
def circuit(alpha, beta, gamma):
    """Total circuit joining each block.

    Args: 
        alpha (float): The first parameter of a U3 gate.
        beta (float):The second parameter of a U3 gate. 
        gamma (float): The third parameter of a U3 gate. 
    
    Returns:
        (float): The expectation value of an observable.
    """
    qml.U3(alpha, beta, gamma, wires=0)
    circuit_left()
    U()
    circuit_right()

    # Here we are returning the expected value with respect to any observable,
    # the choice of observable is not important in this exercise.

    #return qml.expval(0.5 * qml.PauliZ(2) - qml.PauliY(2))
    return qml.probs(wires=2)

In [197]:
for _ in range(10):
    print(circuit(0.1, 0.2, 0.3))

[0.99750208 0.         0.         0.00249792 0.00249792 0.99750208]
[0.99750208 0.         0.         0.00249792 0.00249792 0.99750208]
[0.         0.00249792 0.99750208 0.         0.99750208 0.00249792]
[0.         0.99750208 0.00249792 0.         0.99750208 0.00249792]
[0.99750208 0.         0.         0.00249792 0.00249792 0.99750208]
[0.         0.00249792 0.99750208 0.         0.99750208 0.00249792]
[0.         0.99750208 0.00249792 0.         0.99750208 0.00249792]
[0.         0.00249792 0.99750208 0.         0.99750208 0.00249792]
[0.         0.99750208 0.00249792 0.         0.99750208 0.00249792]
[0.99750208 0.         0.         0.00249792 0.00249792 0.99750208]


In [3]:
dev = qml.device("default.qubit", wires=3)
@qml.qnode(dev)
def ent():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0,1])
    qml.CNOT(wires=[1,2])
    return qml.probs(wires=[0,1,2])

ent()

tensor([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0.5], requires_grad=True)

In [11]:
# Define the quantum teleportation circuit
def teleportation_circuit(params, wires):
    qml.Hadamard(wires=wires[0])
    qml.CNOT(wires=[wires[0], wires[1]])
    qml.CNOT(wires=[wires[1], wires[2]])
    qml.Hadamard(wires=wires[0])
    qml.measure(wires=wires[0])
    qml.measure(wires=wires[1])

    # Apply the Pauli gates depending on the measurement results
    if params[0] == 1:
        qml.PauliX(wires=wires[2])
    if params[1] == 1:
        qml.PauliZ(wires=wires[2])
        
# Set up the device and the initial state of the qubits
dev = qml.device("default.qubit", wires=3)
init_state = np.array([1/np.sqrt(2), 1/np.sqrt(2)], requires_grad=False)

# Apply the teleportation circuit to transfer the state of qubit 1 to qubit 3
@qml.qnode(dev)
def teleportation():
    qml.Hadamard(wires=0)
    teleportation_circuit([0, 0], wires=[0, 1, 2])
    return qml.state()

final_state = teleportation()
print("Final state:\n", final_state)


Final state:
 [0.70710678+0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.70710678+0.j 0.        +0.j 0.        +0.j 0.        +0.j]


In [70]:
d = qml.device('default.qubit', wires=3)
@qml.qnode(d)
def c():
    qml.PauliX(wires=np.random.randint(3))
    # return qml.expval(qml.PauliZ(0) - qml.PauliZ(1))   # for 2-qubit scenario
    return qml.expval(-0.5*qml.PauliZ(0) - qml.PauliZ(1) + 0.5 * qml.PauliZ(2))

In [46]:
np.random.randint(3)

0

In [71]:
for _ in range(10):
    r = c()   # if it is 0, then that means the X gate is applied to q0, if 1, then to q1, and if -2, then to q2
    print(r)

-2.0
0.0
1.0
-2.0
1.0
-2.0
-2.0
-2.0
1.0
0.0


In [72]:
r1 = qml.expval(-0.5*qml.PauliZ(0) - qml.PauliZ(1) + 0.5 * qml.PauliZ(2))

r1

expval(  (-1.0) [Z1]
+ (-0.5) [Z0]
+ (0.5) [Z2])

In [17]:
for i in range(10):
	print("\tIn loop:", i)

print("After loop:", i)

	In loop: 0
	In loop: 1
	In loop: 2
	In loop: 3
	In loop: 4
	In loop: 5
	In loop: 6
	In loop: 7
	In loop: 8
	In loop: 9
After loop: 9


In [30]:
qml.__version__

'0.28.0'

In [94]:
d1 = qml.device('default.qubit', wires=2)
@qml.qnode(d1)
def test1():
    qml.Hadamard(0)
    qml.PauliX(1)
    m = qml.measure(0)
    qml.cond(m, qml.PauliX)(wires=1)
    return qml.probs(wires=1)

In [105]:
p = test1()
p.numpy()[0] == p.numpy()[1]

True

In [83]:
qml.measure??

Signature: qml.measure(wires)
Source:   
def measure(wires):  # TODO: Change name to mid_measure
    """Perform a mid-circuit measurement in the computational basis on the
    supplied qubit.

    Measurement outcomes can be obtained and used to conditionally apply
    operations.

    If a device doesn't support mid-circuit measurements natively, then the
    QNode will apply the :func:`defer_measurements` transform.

    **Example:**

    .. code-block:: python3

        dev = qml.device("default.qubit", wires=2)

        @qml.qnode(dev)
        def func(x, y):
            qml.RY(x, wires=0)
            qml.CNOT(wires=[0, 1])
            m_0 = qml.measure(1)

            qml.cond(m_0, qml.RY)(y, wires=0)
            return qml.probs(wires=[0])

    Executing this QNode:

    >>> pars = np.array([0.643, 0.246], requires_grad=True)
    >>> func(*pars)
    tensor([0.90165331, 0.09834669], requires_grad=True)

    Mid circuit measurements can be manipulated using the following dunder met

In [84]:
qml.cond??

Signature: qml.cond(condition, true_fn, false_fn=None)
Source:   
def cond(condition, true_fn, false_fn=None):
    """Condition a quantum operation on the results of mid-circuit qubit measurements.

    Support for using :func:`~.cond` is device-dependent. If a device doesn't
    support mid-circuit measurements natively, then the QNode will apply the
    :func:`defer_measurements` transform.

    Args:
        condition (.MeasurementValue[bool]): a conditional expression involving a mid-circuit
           measurement value (see :func:`.pennylane.measure`)
        true_fn (callable): The quantum function of PennyLane operation to
            apply if ``condition`` is ``True``
        false_fn (callable): The quantum function of PennyLane operation to
            apply if ``condition`` is ``False``

    Returns:
        function: A new function that applies the conditional equivalent of ``true_fn``. The returned
        function takes the same input arguments as ``true_fn``.

    **Exam

In [112]:
@qml.qnode(d1)
def test2():
    qml.Hadamard(0)
    qml.PauliX(1)
    m = qml.probs(wires=[0,1])
    print(m)

In [113]:
test2()

probs(wires=[0, 1])


QuantumFunctionError: A quantum function must return either a single measurement, or a nonempty sequence of measurements.

In [166]:
de = qml.device("default.qubit", wires=3)
@qml.qnode(de)
def test3(a, b, c):
    qml.U3(a, b, c, wires=0)
    return qml.probs(0)

In [167]:
test3(0.1, 0.2, 0.3)

tensor([0.99750208, 0.00249792], requires_grad=True)